# Generated by Django 4.1.3 on 2022-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
